### ISSUE TITLE
Бесполезное наследование

### ISSUE THREAD

**Issue by igrek8** [Nordwand/Word-Document-Parser#1]
``` java
public class Root extends LinkedList<QuestionDoc> { ... }
```

Класс содержит **3 private static переменные**, а так же наследует поведение коллекции, не описывая никакого специфического поведения отличного от `LinkedList`

Лучше было если не создавать отдельный класс <code>Root</code>, а создать переменную

``` java
LinkedList<QuestionDoc> root
```

и перенести все статичные переменные в независимый стартовый класс например `App` с методом `main`. В добавок стоит разгрузить метод `main`

**Comment by dsirotkin256** [comment]
В следующем коммите будет реализовано. Много статики от которой нет толка в текущей имплементации Root класса.
