### ISSUE TITLE
refactor branch

### ISSUE THREAD

**Issue by dsirotkin256** [Nordwand/Word-Document-Parser#18]
@bzyak  Открыта новая [ветка](https://github.com/Nordwand/Word-Document-Parser/tree/refactor) для глобальных изменений

**Comment by igrek8** [comment]
@Nordwand потом merge сделаем или что?

**Comment by dsirotkin256** [comment]
@bzyak Пока что не нужно мастер засорять. Выходит сомнительный рефактор, убираешь вещи, даже не задумываясь для чего они нужны. Потом у тебя возникнут проблемы при тестировании

**Comment by igrek8** [comment]
Какие могут быть проблемы? Я хочу сделать код очень чистым, понятным и структурным.

Я не вижу никаких потенциальных проблем, до тех пор пока нет запутанного плохо струтурированного кода.

Нужна композиция и контроль.

**Comment by igrek8** [comment]
Ок, мастер не трогаем. Если будешь делать коммиты, то делай их в refactor или просто я иначе не вижу переспектив развивать refactor ветвь, если в дальнейшем не будет merge

**Comment by dsirotkin256** [comment]
@bzyak делай 

> Нужна композиция и контроль.

в refactor branch

**Comment by igrek8** [comment]
Потом будет merge если во время тестирования всё работает?

**Comment by igrek8** [comment]
Я закончу скоро рефактор, я убрал весь multithreading и разделил презентацию от логики
Потому, что иначе это сложно маштабировать.

Я предлагаю после рефактора, продумать хороший пул в виде 4 рабочих, которые через observer будет подписанны к UI. В то время как UI будет иметь только функции для манипулирования интерфейсом и никакой логикой, вся логика будет отправляться другим объектам
