### ISSUE TITLE
Плохие конструкторы

### ISSUE THREAD

**Issue by igrek8** [Nordwand/Word-Document-Parser#4]
``` java
public AnswerDoc(String path) {
    String[] dirs = path.split(":?\\\\");
    docName = dirs[dirs.length - 1];
    this.answerPath = path;
    try {
        this.answerDoc = new HWPFDocument(new FileInputStream(answerPath));
        this.answersExt = new WordExtractor(answerDoc);
    } catch (IOException e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
    }
}
...
public QuestionDoc(String path) {
    ...
    // плохой
    ...
}
```

Выше конструктор плохой, только потому, что он не только инициализирует, а так же обрабатывает строки и исключения

Лучше если конструктор будет вида

``` java
public AnswerDoc(String[] paths) throws IOException { ... }
```

Лучше если конструктор не будет ничего колдовать и если надо будет сразу выкидывать исключения, чем их скрывать от рабочего потока.

``` java
try {
    this.answerDoc = new HWPFDocument(new FileInputStream(answerPath));
    this.answersExt = new WordExtractor(answerDoc);
} catch (IOException e) {
    // TODO Auto-generated catch block
    e.printStackTrace();
}
```

Этот фрагмент чреват тем, что поля `answerDoc` и `answersExt` могут остаться `null` и никто об этом не узнает

ЗЫ: Ведь конструктор для инициализации полей и выделения памяти. Читал, что даже если у вас объявлёно поле на "тяжёлый" класс, лучше его не инициализировать сразу, а только по нужде, через вызов метода

``` java
class A {
    private C c; // немного памяти
    private B b; // много памяти

    public A(C c) { ... } // инициализация полей

    public void initB() { b = new B() }
    public void useB() { ... }
}
...
A a = new A();
...
a.initB();
a.useB();
```

**Comment by dsirotkin256** [comment]
Концепцию понял, сейчас поработаю над этим

**Comment by igrek8** [comment]
@Nordwand как имплементируешь, потом "close and comment"
